// ⚠️ Generated from scripts/__fixtures__/openapi.sample.json, NOT ../backend/openapi.json.
// Re-run `bun run codegen:api` with no --input once that file exists.

// Generated by `bun run codegen:api` from ../backend/openapi.json.
// Do not edit by hand — see frontend/CLAUDE.md's "API codegen" section.
// Regenerate: bun run codegen:api
// Check for drift: bun run codegen:api:check

export interface paths {
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["resetPassword"];
        trace?: never;
    };
    "/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProfile"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            email: string;
            password: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
            passwordConfirmation: string;
            slug?: string;
        };
        ResetPasswordRequest: {
            token: string;
            password: string;
            passwordConfirmation: string;
        };
        UpdateProfileRequest: {
            name: string;
            homeCurrency: string;
        };
        AuthResult: {
            message: string;
            csrfToken: string;
        };
        MessageResult: {
            message: string;
        };
        UploadLimit: {
            used: number;
            limit: number;
            remaining: number;
            resetAt: string;
            canUpload: boolean;
        };
        CurrentSubscription: {
            plan: string;
            limits: {
                uploads: {
                    daily: components["schemas"]["UploadLimit"];
                    monthly: components["schemas"]["UploadLimit"];
                    canUpload: boolean;
                };
            };
        };
        UserProfile: {
            id: string;
            userId: string;
            name: string;
            avatar?: string;
            email?: string;
            homeCurrency: string;
            isOnboarded: boolean;
            createdAt: string;
            currentSubscription: components["schemas"]["CurrentSubscription"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthResult"];
                    };
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MessageResult"];
                    };
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthResult"];
                    };
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserProfile"];
                    };
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserProfile"];
                    };
                };
            };
        };
    };
}
