// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/itsLeonB/cashback/internal/core/service/queue"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskQueue creates a new instance of MockTaskQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskQueue {
	mock := &MockTaskQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskQueue is an autogenerated mock type for the TaskQueue type
type MockTaskQueue struct {
	mock.Mock
}

type MockTaskQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskQueue) EXPECT() *MockTaskQueue_Expecter {
	return &MockTaskQueue_Expecter{mock: &_m.Mock}
}

// AsyncEnqueue provides a mock function for the type MockTaskQueue
func (_mock *MockTaskQueue) AsyncEnqueue(ctx context.Context, message queue.TaskMessage) {
	_mock.Called(ctx, message)
	return
}

// MockTaskQueue_AsyncEnqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsyncEnqueue'
type MockTaskQueue_AsyncEnqueue_Call struct {
	*mock.Call
}

// AsyncEnqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - message queue.TaskMessage
func (_e *MockTaskQueue_Expecter) AsyncEnqueue(ctx any, message any) *MockTaskQueue_AsyncEnqueue_Call {
	return &MockTaskQueue_AsyncEnqueue_Call{Call: _e.mock.On("AsyncEnqueue", ctx, message)}
}

func (_c *MockTaskQueue_AsyncEnqueue_Call) Run(run func(ctx context.Context, message queue.TaskMessage)) *MockTaskQueue_AsyncEnqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 queue.TaskMessage
		if args[1] != nil {
			arg1 = args[1].(queue.TaskMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskQueue_AsyncEnqueue_Call) Return() *MockTaskQueue_AsyncEnqueue_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTaskQueue_AsyncEnqueue_Call) RunAndReturn(run func(ctx context.Context, message queue.TaskMessage)) *MockTaskQueue_AsyncEnqueue_Call {
	_c.Run(run)
	return _c
}

// Enqueue provides a mock function for the type MockTaskQueue
func (_mock *MockTaskQueue) Enqueue(ctx context.Context, message queue.TaskMessage) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, queue.TaskMessage) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskQueue_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockTaskQueue_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - message queue.TaskMessage
func (_e *MockTaskQueue_Expecter) Enqueue(ctx any, message any) *MockTaskQueue_Enqueue_Call {
	return &MockTaskQueue_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, message)}
}

func (_c *MockTaskQueue_Enqueue_Call) Run(run func(ctx context.Context, message queue.TaskMessage)) *MockTaskQueue_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 queue.TaskMessage
		if args[1] != nil {
			arg1 = args[1].(queue.TaskMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskQueue_Enqueue_Call) Return(err error) *MockTaskQueue_Enqueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskQueue_Enqueue_Call) RunAndReturn(run func(ctx context.Context, message queue.TaskMessage) error) *MockTaskQueue_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockTaskQueue
func (_mock *MockTaskQueue) Shutdown() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskQueue_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockTaskQueue_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockTaskQueue_Expecter) Shutdown() *MockTaskQueue_Shutdown_Call {
	return &MockTaskQueue_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockTaskQueue_Shutdown_Call) Run(run func()) *MockTaskQueue_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskQueue_Shutdown_Call) Return(err error) *MockTaskQueue_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskQueue_Shutdown_Call) RunAndReturn(run func() error) *MockTaskQueue_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
