// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/itsLeonB/cashback/internal/domain/entity/users"
	"github.com/itsLeonB/go-crud"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockProfileRepository creates a new instance of MockProfileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileRepository {
	mock := &MockProfileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileRepository is an autogenerated mock type for the ProfileRepository type
type MockProfileRepository struct {
	mock.Mock
}

type MockProfileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileRepository) EXPECT() *MockProfileRepository_Expecter {
	return &MockProfileRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) Delete(ctx context.Context, model users.UserProfile) error {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, users.UserProfile) error); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProfileRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - model users.UserProfile
func (_e *MockProfileRepository_Expecter) Delete(ctx any, model any) *MockProfileRepository_Delete_Call {
	return &MockProfileRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, model)}
}

func (_c *MockProfileRepository_Delete_Call) Run(run func(ctx context.Context, model users.UserProfile)) *MockProfileRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 users.UserProfile
		if args[1] != nil {
			arg1 = args[1].(users.UserProfile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_Delete_Call) Return(err error) *MockProfileRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, model users.UserProfile) error) *MockProfileRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) DeleteMany(ctx context.Context, models []users.UserProfile) error {
	ret := _mock.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []users.UserProfile) error); ok {
		r0 = returnFunc(ctx, models)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileRepository_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type MockProfileRepository_DeleteMany_Call struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []users.UserProfile
func (_e *MockProfileRepository_Expecter) DeleteMany(ctx any, models any) *MockProfileRepository_DeleteMany_Call {
	return &MockProfileRepository_DeleteMany_Call{Call: _e.mock.On("DeleteMany", ctx, models)}
}

func (_c *MockProfileRepository_DeleteMany_Call) Run(run func(ctx context.Context, models []users.UserProfile)) *MockProfileRepository_DeleteMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []users.UserProfile
		if args[1] != nil {
			arg1 = args[1].([]users.UserProfile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_DeleteMany_Call) Return(err error) *MockProfileRepository_DeleteMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileRepository_DeleteMany_Call) RunAndReturn(run func(ctx context.Context, models []users.UserProfile) error) *MockProfileRepository_DeleteMany_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) FindAll(ctx context.Context, spec crud.Specification[users.UserProfile]) ([]users.UserProfile, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []users.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, crud.Specification[users.UserProfile]) ([]users.UserProfile, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, crud.Specification[users.UserProfile]) []users.UserProfile); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.UserProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, crud.Specification[users.UserProfile]) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockProfileRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[users.UserProfile]
func (_e *MockProfileRepository_Expecter) FindAll(ctx any, spec any) *MockProfileRepository_FindAll_Call {
	return &MockProfileRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, spec)}
}

func (_c *MockProfileRepository_FindAll_Call) Run(run func(ctx context.Context, spec crud.Specification[users.UserProfile])) *MockProfileRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 crud.Specification[users.UserProfile]
		if args[1] != nil {
			arg1 = args[1].(crud.Specification[users.UserProfile])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_FindAll_Call) Return(userProfiles []users.UserProfile, err error) *MockProfileRepository_FindAll_Call {
	_c.Call.Return(userProfiles, err)
	return _c
}

func (_c *MockProfileRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context, spec crud.Specification[users.UserProfile]) ([]users.UserProfile, error)) *MockProfileRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) FindByIDs(ctx context.Context, ids []uuid.UUID) ([]users.UserProfile, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []users.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]users.UserProfile, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []users.UserProfile); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.UserProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type MockProfileRepository_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockProfileRepository_Expecter) FindByIDs(ctx any, ids any) *MockProfileRepository_FindByIDs_Call {
	return &MockProfileRepository_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, ids)}
}

func (_c *MockProfileRepository_FindByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockProfileRepository_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_FindByIDs_Call) Return(userProfiles []users.UserProfile, err error) *MockProfileRepository_FindByIDs_Call {
	_c.Call.Return(userProfiles, err)
	return _c
}

func (_c *MockProfileRepository_FindByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) ([]users.UserProfile, error)) *MockProfileRepository_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindFirst provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) FindFirst(ctx context.Context, spec crud.Specification[users.UserProfile]) (users.UserProfile, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindFirst")
	}

	var r0 users.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, crud.Specification[users.UserProfile]) (users.UserProfile, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, crud.Specification[users.UserProfile]) users.UserProfile); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(users.UserProfile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, crud.Specification[users.UserProfile]) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_FindFirst_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFirst'
type MockProfileRepository_FindFirst_Call struct {
	*mock.Call
}

// FindFirst is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[users.UserProfile]
func (_e *MockProfileRepository_Expecter) FindFirst(ctx any, spec any) *MockProfileRepository_FindFirst_Call {
	return &MockProfileRepository_FindFirst_Call{Call: _e.mock.On("FindFirst", ctx, spec)}
}

func (_c *MockProfileRepository_FindFirst_Call) Run(run func(ctx context.Context, spec crud.Specification[users.UserProfile])) *MockProfileRepository_FindFirst_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 crud.Specification[users.UserProfile]
		if args[1] != nil {
			arg1 = args[1].(crud.Specification[users.UserProfile])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_FindFirst_Call) Return(userProfile users.UserProfile, err error) *MockProfileRepository_FindFirst_Call {
	_c.Call.Return(userProfile, err)
	return _c
}

func (_c *MockProfileRepository_FindFirst_Call) RunAndReturn(run func(ctx context.Context, spec crud.Specification[users.UserProfile]) (users.UserProfile, error)) *MockProfileRepository_FindFirst_Call {
	_c.Call.Return(run)
	return _c
}

// FindRealProfiles provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) FindRealProfiles(ctx context.Context) ([]users.UserProfile, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindRealProfiles")
	}

	var r0 []users.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]users.UserProfile, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []users.UserProfile); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.UserProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_FindRealProfiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRealProfiles'
type MockProfileRepository_FindRealProfiles_Call struct {
	*mock.Call
}

// FindRealProfiles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfileRepository_Expecter) FindRealProfiles(ctx any) *MockProfileRepository_FindRealProfiles_Call {
	return &MockProfileRepository_FindRealProfiles_Call{Call: _e.mock.On("FindRealProfiles", ctx)}
}

func (_c *MockProfileRepository_FindRealProfiles_Call) Run(run func(ctx context.Context)) *MockProfileRepository_FindRealProfiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfileRepository_FindRealProfiles_Call) Return(userProfiles []users.UserProfile, err error) *MockProfileRepository_FindRealProfiles_Call {
	_c.Call.Return(userProfiles, err)
	return _c
}

func (_c *MockProfileRepository_FindRealProfiles_Call) RunAndReturn(run func(ctx context.Context) ([]users.UserProfile, error)) *MockProfileRepository_FindRealProfiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetGormInstance provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) GetGormInstance(ctx context.Context) (*gorm.DB, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGormInstance")
	}

	var r0 *gorm.DB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*gorm.DB, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_GetGormInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGormInstance'
type MockProfileRepository_GetGormInstance_Call struct {
	*mock.Call
}

// GetGormInstance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfileRepository_Expecter) GetGormInstance(ctx any) *MockProfileRepository_GetGormInstance_Call {
	return &MockProfileRepository_GetGormInstance_Call{Call: _e.mock.On("GetGormInstance", ctx)}
}

func (_c *MockProfileRepository_GetGormInstance_Call) Run(run func(ctx context.Context)) *MockProfileRepository_GetGormInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfileRepository_GetGormInstance_Call) Return(dB *gorm.DB, err error) *MockProfileRepository_GetGormInstance_Call {
	_c.Call.Return(dB, err)
	return _c
}

func (_c *MockProfileRepository_GetGormInstance_Call) RunAndReturn(run func(ctx context.Context) (*gorm.DB, error)) *MockProfileRepository_GetGormInstance_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) Insert(ctx context.Context, model users.UserProfile) (users.UserProfile, error) {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 users.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, users.UserProfile) (users.UserProfile, error)); ok {
		return returnFunc(ctx, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, users.UserProfile) users.UserProfile); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Get(0).(users.UserProfile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, users.UserProfile) error); ok {
		r1 = returnFunc(ctx, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockProfileRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - model users.UserProfile
func (_e *MockProfileRepository_Expecter) Insert(ctx any, model any) *MockProfileRepository_Insert_Call {
	return &MockProfileRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, model)}
}

func (_c *MockProfileRepository_Insert_Call) Run(run func(ctx context.Context, model users.UserProfile)) *MockProfileRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 users.UserProfile
		if args[1] != nil {
			arg1 = args[1].(users.UserProfile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_Insert_Call) Return(userProfile users.UserProfile, err error) *MockProfileRepository_Insert_Call {
	_c.Call.Return(userProfile, err)
	return _c
}

func (_c *MockProfileRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, model users.UserProfile) (users.UserProfile, error)) *MockProfileRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) InsertMany(ctx context.Context, models []users.UserProfile) ([]users.UserProfile, error) {
	ret := _mock.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 []users.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []users.UserProfile) ([]users.UserProfile, error)); ok {
		return returnFunc(ctx, models)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []users.UserProfile) []users.UserProfile); ok {
		r0 = returnFunc(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.UserProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []users.UserProfile) error); ok {
		r1 = returnFunc(ctx, models)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockProfileRepository_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []users.UserProfile
func (_e *MockProfileRepository_Expecter) InsertMany(ctx any, models any) *MockProfileRepository_InsertMany_Call {
	return &MockProfileRepository_InsertMany_Call{Call: _e.mock.On("InsertMany", ctx, models)}
}

func (_c *MockProfileRepository_InsertMany_Call) Run(run func(ctx context.Context, models []users.UserProfile)) *MockProfileRepository_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []users.UserProfile
		if args[1] != nil {
			arg1 = args[1].([]users.UserProfile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_InsertMany_Call) Return(userProfiles []users.UserProfile, err error) *MockProfileRepository_InsertMany_Call {
	_c.Call.Return(userProfiles, err)
	return _c
}

func (_c *MockProfileRepository_InsertMany_Call) RunAndReturn(run func(ctx context.Context, models []users.UserProfile) ([]users.UserProfile, error)) *MockProfileRepository_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMany provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) SaveMany(ctx context.Context, models []users.UserProfile) ([]users.UserProfile, error) {
	ret := _mock.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for SaveMany")
	}

	var r0 []users.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []users.UserProfile) ([]users.UserProfile, error)); ok {
		return returnFunc(ctx, models)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []users.UserProfile) []users.UserProfile); ok {
		r0 = returnFunc(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.UserProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []users.UserProfile) error); ok {
		r1 = returnFunc(ctx, models)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_SaveMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMany'
type MockProfileRepository_SaveMany_Call struct {
	*mock.Call
}

// SaveMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []users.UserProfile
func (_e *MockProfileRepository_Expecter) SaveMany(ctx any, models any) *MockProfileRepository_SaveMany_Call {
	return &MockProfileRepository_SaveMany_Call{Call: _e.mock.On("SaveMany", ctx, models)}
}

func (_c *MockProfileRepository_SaveMany_Call) Run(run func(ctx context.Context, models []users.UserProfile)) *MockProfileRepository_SaveMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []users.UserProfile
		if args[1] != nil {
			arg1 = args[1].([]users.UserProfile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_SaveMany_Call) Return(userProfiles []users.UserProfile, err error) *MockProfileRepository_SaveMany_Call {
	_c.Call.Return(userProfiles, err)
	return _c
}

func (_c *MockProfileRepository_SaveMany_Call) RunAndReturn(run func(ctx context.Context, models []users.UserProfile) ([]users.UserProfile, error)) *MockProfileRepository_SaveMany_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByName provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) SearchByName(ctx context.Context, query string, limit int) ([]users.UserProfile, error) {
	ret := _mock.Called(ctx, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchByName")
	}

	var r0 []users.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]users.UserProfile, error)); ok {
		return returnFunc(ctx, query, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []users.UserProfile); ok {
		r0 = returnFunc(ctx, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.UserProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, query, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_SearchByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByName'
type MockProfileRepository_SearchByName_Call struct {
	*mock.Call
}

// SearchByName is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - limit int
func (_e *MockProfileRepository_Expecter) SearchByName(ctx any, query any, limit any) *MockProfileRepository_SearchByName_Call {
	return &MockProfileRepository_SearchByName_Call{Call: _e.mock.On("SearchByName", ctx, query, limit)}
}

func (_c *MockProfileRepository_SearchByName_Call) Run(run func(ctx context.Context, query string, limit int)) *MockProfileRepository_SearchByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProfileRepository_SearchByName_Call) Return(userProfiles []users.UserProfile, err error) *MockProfileRepository_SearchByName_Call {
	_c.Call.Return(userProfiles, err)
	return _c
}

func (_c *MockProfileRepository_SearchByName_Call) RunAndReturn(run func(ctx context.Context, query string, limit int) ([]users.UserProfile, error)) *MockProfileRepository_SearchByName_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) Update(ctx context.Context, model users.UserProfile) (users.UserProfile, error) {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 users.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, users.UserProfile) (users.UserProfile, error)); ok {
		return returnFunc(ctx, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, users.UserProfile) users.UserProfile); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Get(0).(users.UserProfile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, users.UserProfile) error); ok {
		r1 = returnFunc(ctx, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProfileRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - model users.UserProfile
func (_e *MockProfileRepository_Expecter) Update(ctx any, model any) *MockProfileRepository_Update_Call {
	return &MockProfileRepository_Update_Call{Call: _e.mock.On("Update", ctx, model)}
}

func (_c *MockProfileRepository_Update_Call) Run(run func(ctx context.Context, model users.UserProfile)) *MockProfileRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 users.UserProfile
		if args[1] != nil {
			arg1 = args[1].(users.UserProfile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_Update_Call) Return(userProfile users.UserProfile, err error) *MockProfileRepository_Update_Call {
	_c.Call.Return(userProfile, err)
	return _c
}

func (_c *MockProfileRepository_Update_Call) RunAndReturn(run func(ctx context.Context, model users.UserProfile) (users.UserProfile, error)) *MockProfileRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFriendshipRepository creates a new instance of MockFriendshipRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFriendshipRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFriendshipRepository {
	mock := &MockFriendshipRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFriendshipRepository is an autogenerated mock type for the FriendshipRepository type
type MockFriendshipRepository struct {
	mock.Mock
}

type MockFriendshipRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFriendshipRepository) EXPECT() *MockFriendshipRepository_Expecter {
	return &MockFriendshipRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) Delete(ctx context.Context, model users.Friendship) error {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, users.Friendship) error); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFriendshipRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFriendshipRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - model users.Friendship
func (_e *MockFriendshipRepository_Expecter) Delete(ctx any, model any) *MockFriendshipRepository_Delete_Call {
	return &MockFriendshipRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, model)}
}

func (_c *MockFriendshipRepository_Delete_Call) Run(run func(ctx context.Context, model users.Friendship)) *MockFriendshipRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 users.Friendship
		if args[1] != nil {
			arg1 = args[1].(users.Friendship)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_Delete_Call) Return(err error) *MockFriendshipRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFriendshipRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, model users.Friendship) error) *MockFriendshipRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) DeleteMany(ctx context.Context, models []users.Friendship) error {
	ret := _mock.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []users.Friendship) error); ok {
		r0 = returnFunc(ctx, models)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFriendshipRepository_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type MockFriendshipRepository_DeleteMany_Call struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []users.Friendship
func (_e *MockFriendshipRepository_Expecter) DeleteMany(ctx any, models any) *MockFriendshipRepository_DeleteMany_Call {
	return &MockFriendshipRepository_DeleteMany_Call{Call: _e.mock.On("DeleteMany", ctx, models)}
}

func (_c *MockFriendshipRepository_DeleteMany_Call) Run(run func(ctx context.Context, models []users.Friendship)) *MockFriendshipRepository_DeleteMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []users.Friendship
		if args[1] != nil {
			arg1 = args[1].([]users.Friendship)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_DeleteMany_Call) Return(err error) *MockFriendshipRepository_DeleteMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFriendshipRepository_DeleteMany_Call) RunAndReturn(run func(ctx context.Context, models []users.Friendship) error) *MockFriendshipRepository_DeleteMany_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) FindAll(ctx context.Context, spec crud.Specification[users.Friendship]) ([]users.Friendship, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []users.Friendship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, crud.Specification[users.Friendship]) ([]users.Friendship, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, crud.Specification[users.Friendship]) []users.Friendship); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.Friendship)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, crud.Specification[users.Friendship]) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockFriendshipRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[users.Friendship]
func (_e *MockFriendshipRepository_Expecter) FindAll(ctx any, spec any) *MockFriendshipRepository_FindAll_Call {
	return &MockFriendshipRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, spec)}
}

func (_c *MockFriendshipRepository_FindAll_Call) Run(run func(ctx context.Context, spec crud.Specification[users.Friendship])) *MockFriendshipRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 crud.Specification[users.Friendship]
		if args[1] != nil {
			arg1 = args[1].(crud.Specification[users.Friendship])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_FindAll_Call) Return(friendships []users.Friendship, err error) *MockFriendshipRepository_FindAll_Call {
	_c.Call.Return(friendships, err)
	return _c
}

func (_c *MockFriendshipRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context, spec crud.Specification[users.Friendship]) ([]users.Friendship, error)) *MockFriendshipRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByProfileIDForUpdate provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) FindAllByProfileIDForUpdate(ctx context.Context, profileID uuid.UUID) ([]users.Friendship, error) {
	ret := _mock.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByProfileIDForUpdate")
	}

	var r0 []users.Friendship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]users.Friendship, error)); ok {
		return returnFunc(ctx, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []users.Friendship); ok {
		r0 = returnFunc(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.Friendship)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_FindAllByProfileIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByProfileIDForUpdate'
type MockFriendshipRepository_FindAllByProfileIDForUpdate_Call struct {
	*mock.Call
}

// FindAllByProfileIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uuid.UUID
func (_e *MockFriendshipRepository_Expecter) FindAllByProfileIDForUpdate(ctx any, profileID any) *MockFriendshipRepository_FindAllByProfileIDForUpdate_Call {
	return &MockFriendshipRepository_FindAllByProfileIDForUpdate_Call{Call: _e.mock.On("FindAllByProfileIDForUpdate", ctx, profileID)}
}

func (_c *MockFriendshipRepository_FindAllByProfileIDForUpdate_Call) Run(run func(ctx context.Context, profileID uuid.UUID)) *MockFriendshipRepository_FindAllByProfileIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_FindAllByProfileIDForUpdate_Call) Return(friendships []users.Friendship, err error) *MockFriendshipRepository_FindAllByProfileIDForUpdate_Call {
	_c.Call.Return(friendships, err)
	return _c
}

func (_c *MockFriendshipRepository_FindAllByProfileIDForUpdate_Call) RunAndReturn(run func(ctx context.Context, profileID uuid.UUID) ([]users.Friendship, error)) *MockFriendshipRepository_FindAllByProfileIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllBySpec provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) FindAllBySpec(ctx context.Context, spec users.FriendshipSpecification) ([]users.Friendship, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindAllBySpec")
	}

	var r0 []users.Friendship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, users.FriendshipSpecification) ([]users.Friendship, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, users.FriendshipSpecification) []users.Friendship); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.Friendship)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, users.FriendshipSpecification) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_FindAllBySpec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllBySpec'
type MockFriendshipRepository_FindAllBySpec_Call struct {
	*mock.Call
}

// FindAllBySpec is a helper method to define mock.On call
//   - ctx context.Context
//   - spec users.FriendshipSpecification
func (_e *MockFriendshipRepository_Expecter) FindAllBySpec(ctx any, spec any) *MockFriendshipRepository_FindAllBySpec_Call {
	return &MockFriendshipRepository_FindAllBySpec_Call{Call: _e.mock.On("FindAllBySpec", ctx, spec)}
}

func (_c *MockFriendshipRepository_FindAllBySpec_Call) Run(run func(ctx context.Context, spec users.FriendshipSpecification)) *MockFriendshipRepository_FindAllBySpec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 users.FriendshipSpecification
		if args[1] != nil {
			arg1 = args[1].(users.FriendshipSpecification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_FindAllBySpec_Call) Return(friendships []users.Friendship, err error) *MockFriendshipRepository_FindAllBySpec_Call {
	_c.Call.Return(friendships, err)
	return _c
}

func (_c *MockFriendshipRepository_FindAllBySpec_Call) RunAndReturn(run func(ctx context.Context, spec users.FriendshipSpecification) ([]users.Friendship, error)) *MockFriendshipRepository_FindAllBySpec_Call {
	_c.Call.Return(run)
	return _c
}

// FindByProfileIDs provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) FindByProfileIDs(ctx context.Context, profileID1 uuid.UUID, profileID2 uuid.UUID) (users.Friendship, error) {
	ret := _mock.Called(ctx, profileID1, profileID2)

	if len(ret) == 0 {
		panic("no return value specified for FindByProfileIDs")
	}

	var r0 users.Friendship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (users.Friendship, error)); ok {
		return returnFunc(ctx, profileID1, profileID2)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) users.Friendship); ok {
		r0 = returnFunc(ctx, profileID1, profileID2)
	} else {
		r0 = ret.Get(0).(users.Friendship)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, profileID1, profileID2)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_FindByProfileIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByProfileIDs'
type MockFriendshipRepository_FindByProfileIDs_Call struct {
	*mock.Call
}

// FindByProfileIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID1 uuid.UUID
//   - profileID2 uuid.UUID
func (_e *MockFriendshipRepository_Expecter) FindByProfileIDs(ctx any, profileID1 any, profileID2 any) *MockFriendshipRepository_FindByProfileIDs_Call {
	return &MockFriendshipRepository_FindByProfileIDs_Call{Call: _e.mock.On("FindByProfileIDs", ctx, profileID1, profileID2)}
}

func (_c *MockFriendshipRepository_FindByProfileIDs_Call) Run(run func(ctx context.Context, profileID1 uuid.UUID, profileID2 uuid.UUID)) *MockFriendshipRepository_FindByProfileIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_FindByProfileIDs_Call) Return(friendship users.Friendship, err error) *MockFriendshipRepository_FindByProfileIDs_Call {
	_c.Call.Return(friendship, err)
	return _c
}

func (_c *MockFriendshipRepository_FindByProfileIDs_Call) RunAndReturn(run func(ctx context.Context, profileID1 uuid.UUID, profileID2 uuid.UUID) (users.Friendship, error)) *MockFriendshipRepository_FindByProfileIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindByProfileIDsForUpdate provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) FindByProfileIDsForUpdate(ctx context.Context, profileID1 uuid.UUID, profileID2 uuid.UUID) (users.Friendship, error) {
	ret := _mock.Called(ctx, profileID1, profileID2)

	if len(ret) == 0 {
		panic("no return value specified for FindByProfileIDsForUpdate")
	}

	var r0 users.Friendship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (users.Friendship, error)); ok {
		return returnFunc(ctx, profileID1, profileID2)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) users.Friendship); ok {
		r0 = returnFunc(ctx, profileID1, profileID2)
	} else {
		r0 = ret.Get(0).(users.Friendship)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, profileID1, profileID2)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_FindByProfileIDsForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByProfileIDsForUpdate'
type MockFriendshipRepository_FindByProfileIDsForUpdate_Call struct {
	*mock.Call
}

// FindByProfileIDsForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID1 uuid.UUID
//   - profileID2 uuid.UUID
func (_e *MockFriendshipRepository_Expecter) FindByProfileIDsForUpdate(ctx any, profileID1 any, profileID2 any) *MockFriendshipRepository_FindByProfileIDsForUpdate_Call {
	return &MockFriendshipRepository_FindByProfileIDsForUpdate_Call{Call: _e.mock.On("FindByProfileIDsForUpdate", ctx, profileID1, profileID2)}
}

func (_c *MockFriendshipRepository_FindByProfileIDsForUpdate_Call) Run(run func(ctx context.Context, profileID1 uuid.UUID, profileID2 uuid.UUID)) *MockFriendshipRepository_FindByProfileIDsForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_FindByProfileIDsForUpdate_Call) Return(friendship users.Friendship, err error) *MockFriendshipRepository_FindByProfileIDsForUpdate_Call {
	_c.Call.Return(friendship, err)
	return _c
}

func (_c *MockFriendshipRepository_FindByProfileIDsForUpdate_Call) RunAndReturn(run func(ctx context.Context, profileID1 uuid.UUID, profileID2 uuid.UUID) (users.Friendship, error)) *MockFriendshipRepository_FindByProfileIDsForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// FindFirst provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) FindFirst(ctx context.Context, spec crud.Specification[users.Friendship]) (users.Friendship, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindFirst")
	}

	var r0 users.Friendship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, crud.Specification[users.Friendship]) (users.Friendship, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, crud.Specification[users.Friendship]) users.Friendship); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(users.Friendship)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, crud.Specification[users.Friendship]) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_FindFirst_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFirst'
type MockFriendshipRepository_FindFirst_Call struct {
	*mock.Call
}

// FindFirst is a helper method to define mock.On call
//   - ctx context.Context
//   - spec crud.Specification[users.Friendship]
func (_e *MockFriendshipRepository_Expecter) FindFirst(ctx any, spec any) *MockFriendshipRepository_FindFirst_Call {
	return &MockFriendshipRepository_FindFirst_Call{Call: _e.mock.On("FindFirst", ctx, spec)}
}

func (_c *MockFriendshipRepository_FindFirst_Call) Run(run func(ctx context.Context, spec crud.Specification[users.Friendship])) *MockFriendshipRepository_FindFirst_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 crud.Specification[users.Friendship]
		if args[1] != nil {
			arg1 = args[1].(crud.Specification[users.Friendship])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_FindFirst_Call) Return(friendship users.Friendship, err error) *MockFriendshipRepository_FindFirst_Call {
	_c.Call.Return(friendship, err)
	return _c
}

func (_c *MockFriendshipRepository_FindFirst_Call) RunAndReturn(run func(ctx context.Context, spec crud.Specification[users.Friendship]) (users.Friendship, error)) *MockFriendshipRepository_FindFirst_Call {
	_c.Call.Return(run)
	return _c
}

// FindFirstBySpec provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) FindFirstBySpec(ctx context.Context, spec users.FriendshipSpecification) (users.Friendship, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindFirstBySpec")
	}

	var r0 users.Friendship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, users.FriendshipSpecification) (users.Friendship, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, users.FriendshipSpecification) users.Friendship); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(users.Friendship)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, users.FriendshipSpecification) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_FindFirstBySpec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFirstBySpec'
type MockFriendshipRepository_FindFirstBySpec_Call struct {
	*mock.Call
}

// FindFirstBySpec is a helper method to define mock.On call
//   - ctx context.Context
//   - spec users.FriendshipSpecification
func (_e *MockFriendshipRepository_Expecter) FindFirstBySpec(ctx any, spec any) *MockFriendshipRepository_FindFirstBySpec_Call {
	return &MockFriendshipRepository_FindFirstBySpec_Call{Call: _e.mock.On("FindFirstBySpec", ctx, spec)}
}

func (_c *MockFriendshipRepository_FindFirstBySpec_Call) Run(run func(ctx context.Context, spec users.FriendshipSpecification)) *MockFriendshipRepository_FindFirstBySpec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 users.FriendshipSpecification
		if args[1] != nil {
			arg1 = args[1].(users.FriendshipSpecification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_FindFirstBySpec_Call) Return(friendship users.Friendship, err error) *MockFriendshipRepository_FindFirstBySpec_Call {
	_c.Call.Return(friendship, err)
	return _c
}

func (_c *MockFriendshipRepository_FindFirstBySpec_Call) RunAndReturn(run func(ctx context.Context, spec users.FriendshipSpecification) (users.Friendship, error)) *MockFriendshipRepository_FindFirstBySpec_Call {
	_c.Call.Return(run)
	return _c
}

// GetGormInstance provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) GetGormInstance(ctx context.Context) (*gorm.DB, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGormInstance")
	}

	var r0 *gorm.DB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*gorm.DB, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_GetGormInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGormInstance'
type MockFriendshipRepository_GetGormInstance_Call struct {
	*mock.Call
}

// GetGormInstance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFriendshipRepository_Expecter) GetGormInstance(ctx any) *MockFriendshipRepository_GetGormInstance_Call {
	return &MockFriendshipRepository_GetGormInstance_Call{Call: _e.mock.On("GetGormInstance", ctx)}
}

func (_c *MockFriendshipRepository_GetGormInstance_Call) Run(run func(ctx context.Context)) *MockFriendshipRepository_GetGormInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_GetGormInstance_Call) Return(dB *gorm.DB, err error) *MockFriendshipRepository_GetGormInstance_Call {
	_c.Call.Return(dB, err)
	return _c
}

func (_c *MockFriendshipRepository_GetGormInstance_Call) RunAndReturn(run func(ctx context.Context) (*gorm.DB, error)) *MockFriendshipRepository_GetGormInstance_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) Insert(ctx context.Context, friendship users.Friendship) (users.Friendship, error) {
	ret := _mock.Called(ctx, friendship)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 users.Friendship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, users.Friendship) (users.Friendship, error)); ok {
		return returnFunc(ctx, friendship)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, users.Friendship) users.Friendship); ok {
		r0 = returnFunc(ctx, friendship)
	} else {
		r0 = ret.Get(0).(users.Friendship)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, users.Friendship) error); ok {
		r1 = returnFunc(ctx, friendship)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockFriendshipRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - friendship users.Friendship
func (_e *MockFriendshipRepository_Expecter) Insert(ctx any, friendship any) *MockFriendshipRepository_Insert_Call {
	return &MockFriendshipRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, friendship)}
}

func (_c *MockFriendshipRepository_Insert_Call) Run(run func(ctx context.Context, friendship users.Friendship)) *MockFriendshipRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 users.Friendship
		if args[1] != nil {
			arg1 = args[1].(users.Friendship)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_Insert_Call) Return(friendship1 users.Friendship, err error) *MockFriendshipRepository_Insert_Call {
	_c.Call.Return(friendship1, err)
	return _c
}

func (_c *MockFriendshipRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, friendship users.Friendship) (users.Friendship, error)) *MockFriendshipRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) InsertMany(ctx context.Context, models []users.Friendship) ([]users.Friendship, error) {
	ret := _mock.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 []users.Friendship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []users.Friendship) ([]users.Friendship, error)); ok {
		return returnFunc(ctx, models)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []users.Friendship) []users.Friendship); ok {
		r0 = returnFunc(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.Friendship)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []users.Friendship) error); ok {
		r1 = returnFunc(ctx, models)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockFriendshipRepository_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []users.Friendship
func (_e *MockFriendshipRepository_Expecter) InsertMany(ctx any, models any) *MockFriendshipRepository_InsertMany_Call {
	return &MockFriendshipRepository_InsertMany_Call{Call: _e.mock.On("InsertMany", ctx, models)}
}

func (_c *MockFriendshipRepository_InsertMany_Call) Run(run func(ctx context.Context, models []users.Friendship)) *MockFriendshipRepository_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []users.Friendship
		if args[1] != nil {
			arg1 = args[1].([]users.Friendship)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_InsertMany_Call) Return(friendships []users.Friendship, err error) *MockFriendshipRepository_InsertMany_Call {
	_c.Call.Return(friendships, err)
	return _c
}

func (_c *MockFriendshipRepository_InsertMany_Call) RunAndReturn(run func(ctx context.Context, models []users.Friendship) ([]users.Friendship, error)) *MockFriendshipRepository_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// RepointFriendships provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) RepointFriendships(ctx context.Context, anonProfileID uuid.UUID, realProfileID uuid.UUID) error {
	ret := _mock.Called(ctx, anonProfileID, realProfileID)

	if len(ret) == 0 {
		panic("no return value specified for RepointFriendships")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, anonProfileID, realProfileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFriendshipRepository_RepointFriendships_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepointFriendships'
type MockFriendshipRepository_RepointFriendships_Call struct {
	*mock.Call
}

// RepointFriendships is a helper method to define mock.On call
//   - ctx context.Context
//   - anonProfileID uuid.UUID
//   - realProfileID uuid.UUID
func (_e *MockFriendshipRepository_Expecter) RepointFriendships(ctx any, anonProfileID any, realProfileID any) *MockFriendshipRepository_RepointFriendships_Call {
	return &MockFriendshipRepository_RepointFriendships_Call{Call: _e.mock.On("RepointFriendships", ctx, anonProfileID, realProfileID)}
}

func (_c *MockFriendshipRepository_RepointFriendships_Call) Run(run func(ctx context.Context, anonProfileID uuid.UUID, realProfileID uuid.UUID)) *MockFriendshipRepository_RepointFriendships_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_RepointFriendships_Call) Return(err error) *MockFriendshipRepository_RepointFriendships_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFriendshipRepository_RepointFriendships_Call) RunAndReturn(run func(ctx context.Context, anonProfileID uuid.UUID, realProfileID uuid.UUID) error) *MockFriendshipRepository_RepointFriendships_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMany provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) SaveMany(ctx context.Context, models []users.Friendship) ([]users.Friendship, error) {
	ret := _mock.Called(ctx, models)

	if len(ret) == 0 {
		panic("no return value specified for SaveMany")
	}

	var r0 []users.Friendship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []users.Friendship) ([]users.Friendship, error)); ok {
		return returnFunc(ctx, models)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []users.Friendship) []users.Friendship); ok {
		r0 = returnFunc(ctx, models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.Friendship)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []users.Friendship) error); ok {
		r1 = returnFunc(ctx, models)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_SaveMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMany'
type MockFriendshipRepository_SaveMany_Call struct {
	*mock.Call
}

// SaveMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []users.Friendship
func (_e *MockFriendshipRepository_Expecter) SaveMany(ctx any, models any) *MockFriendshipRepository_SaveMany_Call {
	return &MockFriendshipRepository_SaveMany_Call{Call: _e.mock.On("SaveMany", ctx, models)}
}

func (_c *MockFriendshipRepository_SaveMany_Call) Run(run func(ctx context.Context, models []users.Friendship)) *MockFriendshipRepository_SaveMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []users.Friendship
		if args[1] != nil {
			arg1 = args[1].([]users.Friendship)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_SaveMany_Call) Return(friendships []users.Friendship, err error) *MockFriendshipRepository_SaveMany_Call {
	_c.Call.Return(friendships, err)
	return _c
}

func (_c *MockFriendshipRepository_SaveMany_Call) RunAndReturn(run func(ctx context.Context, models []users.Friendship) ([]users.Friendship, error)) *MockFriendshipRepository_SaveMany_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockFriendshipRepository
func (_mock *MockFriendshipRepository) Update(ctx context.Context, model users.Friendship) (users.Friendship, error) {
	ret := _mock.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 users.Friendship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, users.Friendship) (users.Friendship, error)); ok {
		return returnFunc(ctx, model)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, users.Friendship) users.Friendship); ok {
		r0 = returnFunc(ctx, model)
	} else {
		r0 = ret.Get(0).(users.Friendship)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, users.Friendship) error); ok {
		r1 = returnFunc(ctx, model)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFriendshipRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockFriendshipRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - model users.Friendship
func (_e *MockFriendshipRepository_Expecter) Update(ctx any, model any) *MockFriendshipRepository_Update_Call {
	return &MockFriendshipRepository_Update_Call{Call: _e.mock.On("Update", ctx, model)}
}

func (_c *MockFriendshipRepository_Update_Call) Run(run func(ctx context.Context, model users.Friendship)) *MockFriendshipRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 users.Friendship
		if args[1] != nil {
			arg1 = args[1].(users.Friendship)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFriendshipRepository_Update_Call) Return(friendship users.Friendship, err error) *MockFriendshipRepository_Update_Call {
	_c.Call.Return(friendship, err)
	return _c
}

func (_c *MockFriendshipRepository_Update_Call) RunAndReturn(run func(ctx context.Context, model users.Friendship) (users.Friendship, error)) *MockFriendshipRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
