// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/itsLeonB/cashback/internal/core/service/langfuse"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetPrompt provides a mock function for the type MockClient
func (_mock *MockClient) GetPrompt(ctx context.Context, name string, opts ...langfuse.GetPromptOptions) (*langfuse.Prompt, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, name, opts)
	} else {
		tmpRet = _mock.Called(ctx, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetPrompt")
	}

	var r0 *langfuse.Prompt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...langfuse.GetPromptOptions) (*langfuse.Prompt, error)); ok {
		return returnFunc(ctx, name, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...langfuse.GetPromptOptions) *langfuse.Prompt); ok {
		r0 = returnFunc(ctx, name, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*langfuse.Prompt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...langfuse.GetPromptOptions) error); ok {
		r1 = returnFunc(ctx, name, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetPrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrompt'
type MockClient_GetPrompt_Call struct {
	*mock.Call
}

// GetPrompt is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts ...langfuse.GetPromptOptions
func (_e *MockClient_Expecter) GetPrompt(ctx any, name any, opts ...any) *MockClient_GetPrompt_Call {
	return &MockClient_GetPrompt_Call{Call: _e.mock.On("GetPrompt",
		append([]any{ctx, name}, opts...)...)}
}

func (_c *MockClient_GetPrompt_Call) Run(run func(ctx context.Context, name string, opts ...langfuse.GetPromptOptions)) *MockClient_GetPrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []langfuse.GetPromptOptions
		var variadicArgs []langfuse.GetPromptOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]langfuse.GetPromptOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_GetPrompt_Call) Return(prompt *langfuse.Prompt, err error) *MockClient_GetPrompt_Call {
	_c.Call.Return(prompt, err)
	return _c
}

func (_c *MockClient_GetPrompt_Call) RunAndReturn(run func(ctx context.Context, name string, opts ...langfuse.GetPromptOptions) (*langfuse.Prompt, error)) *MockClient_GetPrompt_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockClient
func (_mock *MockClient) Shutdown() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockClient_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockClient_Expecter) Shutdown() *MockClient_Shutdown_Call {
	return &MockClient_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockClient_Shutdown_Call) Run(run func()) *MockClient_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Shutdown_Call) Return(err error) *MockClient_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Shutdown_Call) RunAndReturn(run func() error) *MockClient_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
