// scripts/codegen-api.ts
//
// Generates frontend/src/lib/api/schema.gen.ts from the backend's OpenAPI
// document using openapi-typescript, and implements the drift check that
// backs `bun run codegen:api:check` (see frontend/CLAUDE.md's "API codegen"
// section for the full contract).
//
// Usage:
//   bun scripts/codegen-api.ts generate [--input=<path>] [--output=<path>]
//   bun scripts/codegen-api.ts check    [--input=<path>] [--output=<path>]
//
// --input/--output default to the real backend document
// (../backend/openapi.json, repo-root-relative) and the checked-in
// src/lib/api/schema.gen.ts. Only override them for local testing against a
// fixture (see scripts/codegen-api.test.ts).
//
// No network: the input is always read from a local file with fs and
// parsed ourselves before being handed to openapi-typescript as a plain
// object, never as a URL/string it could resolve remotely.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

const SCRIPT_DIR = import.meta.dir;

// frontend/scripts -> ../.. -> repo root -> backend/openapi.json
export const DEFAULT_INPUT_PATH = path.resolve(SCRIPT_DIR, "..", "..", "backend", "openapi.json");
export const DEFAULT_OUTPUT_PATH = path.resolve(SCRIPT_DIR, "..", "src", "lib", "api", "schema.gen.ts");

const GENERATED_NOTE =
  "// Generated by `bun run codegen:api` from ../backend/openapi.json.\n" +
  "// Do not edit by hand — see frontend/CLAUDE.md's \"API codegen\" section.\n" +
  "// Regenerate: bun run codegen:api\n" +
  "// Check for drift: bun run codegen:api:check\n\n";

export interface CodegenOptions {
  inputPath: string;
  outputPath: string;
}

export interface DriftCheckResult {
  ok: boolean;
  message: string;
}

function missingInputMessage(inputPath: string): string {
  return (
    `OpenAPI document not found at ${inputPath}.\n` +
    "This is expected until the backend has produced backend/openapi.json " +
    "(see frontend/CLAUDE.md's \"API codegen\" section)."
  );
}

// Reads and parses the OpenAPI document ourselves, then hands the resulting
// object to openapi-typescript, rather than passing it a path/URL — this is
// what guarantees generation never makes a network request, independent of
// how openapi-typescript's own input handling behaves.
export async function generateSchemaSource(inputPath: string): Promise<string> {
  if (!fs.existsSync(inputPath)) {
    throw new Error(missingInputMessage(inputPath));
  }

  const raw = fs.readFileSync(inputPath, "utf-8");
  const schema = JSON.parse(raw);
  const ast = await openapiTS(schema);

  let source = GENERATED_NOTE + astToString(ast);

  // Flag output generated from a non-default input so it's never mistaken
  // for a real backend/openapi.json snapshot (e.g. a fixture-derived file
  // left checked in ahead of that file existing — see CASH-19).
  if (path.resolve(inputPath) !== DEFAULT_INPUT_PATH) {
    source =
      `// ⚠️ Generated from ${path.relative(process.cwd(), inputPath)}, NOT ../backend/openapi.json.\n` +
      "// Re-run `bun run codegen:api` with no --input once that file exists.\n\n" +
      source;
  }

  return source;
}

export async function writeSchema(options: CodegenOptions): Promise<string> {
  const source = await generateSchemaSource(options.inputPath);
  fs.mkdirSync(path.dirname(options.outputPath), { recursive: true });
  fs.writeFileSync(options.outputPath, source);
  return source;
}

// Regenerates to a temp file and compares file contents — never `git diff`,
// so this behaves identically in CI and a dirty local working tree.
export async function checkSchemaDrift(options: CodegenOptions): Promise<DriftCheckResult> {
  const fresh = await generateSchemaSource(options.inputPath);
  const relOutput = path.relative(process.cwd(), options.outputPath);

  if (!fs.existsSync(options.outputPath)) {
    return {
      ok: false,
      message: `${relOutput} does not exist yet. Run \`bun run codegen:api\` first.`,
    };
  }

  const checkedIn = fs.readFileSync(options.outputPath, "utf-8");

  if (fresh === checkedIn) {
    return { ok: true, message: `${relOutput} is up to date with ../backend/openapi.json.` };
  }

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "cashus-codegen-api-"));
  const tmpPath = path.join(tmpDir, "schema.gen.ts");
  fs.writeFileSync(tmpPath, fresh);

  return {
    ok: false,
    message:
      `${relOutput} is stale relative to ../backend/openapi.json.\n` +
      `Freshly generated output was written to ${tmpPath} for comparison.\n` +
      "Run `bun run codegen:api` to update it.",
  };
}

interface ParsedArgs {
  mode: "generate" | "check";
  options: CodegenOptions;
}

export function parseArgs(argv: string[]): ParsedArgs {
  const mode = argv[0];
  if (mode !== "generate" && mode !== "check") {
    throw new Error(`Unknown mode "${mode ?? ""}". Expected "generate" or "check".`);
  }

  let inputPath = DEFAULT_INPUT_PATH;
  let outputPath = DEFAULT_OUTPUT_PATH;

  for (const arg of argv.slice(1)) {
    if (arg.startsWith("--input=")) {
      inputPath = path.resolve(process.cwd(), arg.slice("--input=".length));
    } else if (arg.startsWith("--output=")) {
      outputPath = path.resolve(process.cwd(), arg.slice("--output=".length));
    }
  }

  return { mode, options: { inputPath, outputPath } };
}

async function main(): Promise<void> {
  const { mode, options } = parseArgs(process.argv.slice(2));

  if (mode === "generate") {
    await writeSchema(options);
    console.log(`Wrote ${path.relative(process.cwd(), options.outputPath)}`);
    return;
  }

  const result = await checkSchemaDrift(options);
  console.log(result.message);
  if (!result.ok) {
    process.exit(1);
  }
}

if (import.meta.main) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
