#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "CASH-10: preview deployment pipeline setup"

# ── Stage 1: prerequisites ─────────────────────────────────────────────────
stage "Prerequisites"
say "This wizard sets up the credentials the preview-environments GitHub"
say "Actions workflow (.github/workflows/preview-environments.yml) needs:"
say "a Neon API key, a Railway CI token, and a Vercel CI token — plus"
say "enabling Railway's PR Deploys feature on the backend project."
say ""
say "It writes eight GitHub Actions repo secrets on itsLeonB/cashus via the"
say "gh CLI. Nothing is written to a local .env file — these are CI-only."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "${GREEN}✓ gh is installed and authenticated.${RESET}"
else
  warn "gh is not installed or not authenticated."
  say "Install: https://cli.github.com — then run 'gh auth login'."
  say "You can still continue and set secrets manually afterwards; this"
  say "wizard will tell you the exact 'gh secret set' command to run."
fi
pause "Ready?"

# ── Stage 2: Neon ───────────────────────────────────────────────────────────
stage "Neon: API key + project ID + role/database"
say "The workflow creates/deletes a database branch per PR via the Neon API."
open_url "https://console.neon.tech"
step "Open the cashus production project, then note its Project ID"
step "(Project → Settings → General → Project ID, looks like a short slug)."
ask NEON_PROJECT_ID "Paste the Neon project ID:"
step "Now open the production branch's Roles & Databases tab and note the"
step "existing role name and database name the backend actually connects"
step "with (matches DB_USER/DB_NAME in backend/.env.example) — the workflow"
step "reuses these on each PR's branch rather than creating new ones,"
step "since Neon branching already copies them from production."
ask NEON_ROLE_NAME "Paste the Neon role name:"
ask NEON_DATABASE_NAME "Paste the Neon database name:"
step "Now go to Account Settings → API keys → Create new API key."
open_url "https://console.neon.tech/app/settings/api-keys"
ask_secret NEON_API_KEY "Paste the Neon API key:"
set_secret NEON_PROJECT_ID "$NEON_PROJECT_ID"
set_secret NEON_ROLE_NAME "$NEON_ROLE_NAME"
set_secret NEON_DATABASE_NAME "$NEON_DATABASE_NAME"
set_secret NEON_API_KEY "$NEON_API_KEY"

# ── Stage 3: Railway ────────────────────────────────────────────────────────
stage "Railway: enable PR Deploys + CI token"
say "Railway auto-provisions an ephemeral 'PR environment' per pull request"
say "once PR Deploys is enabled on the cashus-backend project. The workflow"
say "then finds that environment and pushes each PR's Neon credentials into"
say "it."
say ""
warn "The CI token below MUST be account-scoped, not a project token."
say "Railway project tokens are pinned to the one environment they were"
say "created for and can't see or act on a PR's dynamically-created"
say "environment (confirmed against a live run — a project token could only"
say "ever list the environment it was scoped to). An account token can see"
say "everything on the account, which is broader than this workflow"
say "strictly needs; if that's a concern, use a Railway account dedicated"
say "to CI rather than a personal one."
say ""
step "Create an account token at:"
open_url "https://railway.com/account/tokens"
ask_secret RAILWAY_API_TOKEN "Paste the Railway account token:"
say ""
if confirm "Enable PR Deploys on the cashus-backend project now, using this token?"; then
  ask RAILWAY_BACKEND_PROJECT_ID "Paste the cashus-backend Railway project ID (Project Settings → General):"
  say "Calling projectUpdate to set prDeploys: true ..."
  if curl -fsS -X POST "https://backboard.railway.com/graphql/v2" \
      -H "Authorization: Bearer ${RAILWAY_API_TOKEN}" \
      -H "Content-Type: application/json" \
      -d "$(printf '{"query":"mutation updateProject($id: String!, $input: ProjectUpdateInput!) { projectUpdate(id: $id, input: $input) { id prDeploys } }","variables":{"id":"%s","input":{"prDeploys":true}}}' "$RAILWAY_BACKEND_PROJECT_ID")" \
      | grep -q '"prDeploys":true'; then
    say "${GREEN}✓ PR Deploys enabled on the Railway project.${RESET}"
  else
    warn "Could not confirm PR Deploys was enabled — check the dashboard instead:"
    say "Project → Settings → Environments → enable 'PR Environments'."
  fi
else
  say "Enable it by hand instead:"
  step "Project → Settings → Environments → enable 'PR Environments'."
  open_url "https://railway.com/dashboard"
  pause "Press Enter once PR Deploys is enabled."
fi
set_secret RAILWAY_API_TOKEN "$RAILWAY_API_TOKEN"

# ── Stage 4: Vercel ──────────────────────────────────────────────────────────
stage "Vercel: CI token + org/project IDs"
say "The workflow points each PR's Vercel preview build at that PR's"
say "Railway API URL by setting a branch-scoped VITE_API_BASE_URL and"
say "triggering a fresh preview deployment via the Vercel CLI."
open_url "https://vercel.com/account/tokens"
step "Create Token → copy it."
ask_secret VERCEL_TOKEN "Paste the Vercel token:"
say ""
say "For the org/project IDs, either read them off the dashboard"
say "(Project → Settings → General), or run this locally and read"
say "frontend/.vercel/project.json:"
note "  cd frontend && vercel link"
ask VERCEL_ORG_ID "Paste the Vercel org ID (orgId):"
ask VERCEL_PROJECT_ID "Paste the Vercel project ID (projectId) for the frontend:"
set_secret VERCEL_TOKEN "$VERCEL_TOKEN"
set_secret VERCEL_ORG_ID "$VERCEL_ORG_ID"
set_secret VERCEL_PROJECT_ID "$VERCEL_PROJECT_ID"

# ── Stage 5: verify ──────────────────────────────────────────────────────────
stage "Verify"
say "Checking which of the eight secrets are now set on the repo..."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  gh secret list | grep -E '^(NEON_API_KEY|NEON_PROJECT_ID|NEON_ROLE_NAME|NEON_DATABASE_NAME|RAILWAY_API_TOKEN|VERCEL_TOKEN|VERCEL_ORG_ID|VERCEL_PROJECT_ID)\b' || true
else
  warn "gh not ready — run 'gh secret list' yourself once authenticated."
fi
say ""
say "Once all eight are set and Railway PR Deploys is on, open a PR (from a"
say "branch in this repo, not a fork) and the"
say "'Preview Environments' workflow will provision Neon + Railway + Vercel"
say "automatically. See docs/deployment/preview-environments.md for details."
# ──────────────────────────────────────────────────────────────────────────

finish
