// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/google/wire"
	"github.com/itsLeonB/cashback/internal/provider/admin"
)

// Injectors from wire.go:

func InitializeProviders() (*Providers, func(), error) {
	dataSources, cleanup, err := ProvideDataSource()
	if err != nil {
		return nil, nil, err
	}
	db := dataSources.Gorm
	transactor := ProvideTransactor(db)
	repositories := ProvideRepositories(db, transactor)
	llmService := ProvideLLMService()
	mailService := ProvideMailService()
	storageRepository, cleanup2, err := ProvideGCSStorage()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	imageService := ProvideImageService(storageRepository)
	conn, cleanup3, err := ProvideNATSConn()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	jetStream, err := ProvideJetStream(conn)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	stateStore, cleanup4, err := ProvideStateStore(jetStream)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ocrService, cleanup5, err := ProvideOCRClient()
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	taskQueue, cleanup6 := ProvideTaskQueue(jetStream)
	client := ProvideWebPushClient()
	langfuseClient, cleanup7 := ProvideLangfuseClient()
	coreServices := &CoreServices{
		LLM:       llmService,
		Mail:      mailService,
		Image:     imageService,
		State:     stateStore,
		OCR:       ocrService,
		Storage:   storageRepository,
		Queue:     taskQueue,
		WebPush:   client,
		Langfuse:  langfuseClient,
		NATSConn:  conn,
		JetStream: jetStream,
	}
	services, cleanup8, err := ProvideServices(repositories, coreServices)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	adminRepositories := admin.ProvideRepositories(db, transactor)
	config := ProvideAdminConfig()
	adminServices, err := admin.ProvideServices(adminRepositories, config)
	if err != nil {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	providers := &Providers{
		DataSources:   dataSources,
		Repositories:  repositories,
		CoreServices:  coreServices,
		Services:      services,
		AdminRepos:    adminRepositories,
		AdminServices: adminServices,
	}
	return providers, func() {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// ProviderSet composes every provider set in this package plus the admin
// sub-package's, and assembles the top-level Providers struct from them.
//
// The admin config is supplied via ProvideAdminConfig, a normal runtime
// provider function, not wire.Value(adminConfig.Global): wire.Value would
// capture admin.Global through a package-level var initializer that runs at
// package-init time, before main() calls config.Load() (which is what
// actually populates admin.Global) — permanently freezing it at nil. See
// ProvideAdminConfig's doc comment for the full explanation.
var ProviderSet = wire.NewSet(
	DataSourceSet,
	TransactorSet,
	RepositorySet,
	CoreServiceSet,
	ServiceSet, admin.ProviderSet, ProvideAdminConfig, wire.FieldsOf(new(*DataSources), "Gorm"), wire.Struct(new(Providers), "*"),
)
